#!/bin/bash
set -e

echo "=== SSH Multi-Account Setup ==="
echo ""

# ============================================
# CONFIGURATION - Edit these for your accounts
# ============================================
PERSONAL_EMAIL="sam@personal.com"
PERSONAL_GITHUB_USER="SamBailey6194"

SYNTEK_EMAIL="sam@syntek.com"
SYNTEK_GITHUB_USER="syntek-studio"

MG_EMAIL="sam@missionalgen.com"
MG_GITHUB_USER="sam-missionalgen"

# ============================================
# ENVIRONMENT DETECTION
# ============================================
IS_WSL=false
if grep -qEi "(Microsoft|WSL)" /proc/version 2>/dev/null; then
    IS_WSL=true
    echo "Environment: WSL (Windows Subsystem for Linux)"
else
    echo "Environment: Native Linux"
fi
echo ""

# ============================================
# CREATE SSH DIRECTORY
# ============================================
mkdir -p ~/.ssh
chmod 700 ~/.ssh

# ============================================
# GENERATE SSH KEYS
# ============================================
generate_key() {
    local key_path="$1"
    local email="$2"
    local name="$3"

    if [ -f "$key_path" ]; then
        echo "✓ $name key already exists: $key_path"
    else
        echo "→ Generating $name key..."
        ssh-keygen -t ed25519 -f "$key_path" -C "$email" -N ""
        echo "✓ $name key created: $key_path"
    fi
}

echo "=== Generating SSH Keys ==="
echo ""
generate_key ~/.ssh/id_ed25519_personal "$PERSONAL_EMAIL" "Personal"
generate_key ~/.ssh/id_ed25519_syntek "$SYNTEK_EMAIL" "Syntek"
generate_key ~/.ssh/id_ed25519_mg "$MG_EMAIL" "Missional Gen"
echo ""

# ============================================
# CREATE SSH CONFIG
# ============================================
echo "=== Creating SSH Config ==="

SSH_CONFIG="# GitHub Multi-Account SSH Configuration
# Generated by zedconfig/ssh-setup.sh

# Personal GitHub ($PERSONAL_GITHUB_USER)
Host github-personal
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519_personal
    IdentitiesOnly yes

# Syntek GitHub ($SYNTEK_GITHUB_USER)
Host github-syntek
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519_syntek
    IdentitiesOnly yes

# Missional Gen GitHub ($MG_GITHUB_USER)
Host github-missionalgen
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519_mg
    IdentitiesOnly yes

# Default GitHub (fallback to personal)
Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519_personal
    IdentitiesOnly yes
"

if [ -f ~/.ssh/config ]; then
    echo "→ Backing up existing config to ~/.ssh/config.bak"
    cp ~/.ssh/config ~/.ssh/config.bak
fi

echo "$SSH_CONFIG" > ~/.ssh/config
chmod 600 ~/.ssh/config
echo "✓ SSH config created: ~/.ssh/config"
echo ""

# ============================================
# SET CORRECT PERMISSIONS
# ============================================
echo "=== Setting Permissions ==="
chmod 600 ~/.ssh/id_ed25519_*
chmod 644 ~/.ssh/id_ed25519_*.pub
echo "✓ Permissions set"
echo ""

# ============================================
# START SSH AGENT
# ============================================
echo "=== Adding Keys to SSH Agent ==="
eval "$(ssh-agent -s)" > /dev/null 2>&1
ssh-add ~/.ssh/id_ed25519_personal 2>/dev/null && echo "✓ Personal key added"
ssh-add ~/.ssh/id_ed25519_syntek 2>/dev/null && echo "✓ Syntek key added"
ssh-add ~/.ssh/id_ed25519_mg 2>/dev/null && echo "✓ Missional Gen key added"
echo ""

# ============================================
# PRINT PUBLIC KEYS
# ============================================
echo "============================================"
echo "=== PUBLIC KEYS - Add these to GitHub ==="
echo "============================================"
echo ""
echo "-------------------------------------------"
echo "PERSONAL ($PERSONAL_GITHUB_USER)"
echo "https://github.com/settings/keys"
echo "-------------------------------------------"
cat ~/.ssh/id_ed25519_personal.pub
echo ""
echo "-------------------------------------------"
echo "SYNTEK ($SYNTEK_GITHUB_USER)"
echo "https://github.com/settings/keys"
echo "-------------------------------------------"
cat ~/.ssh/id_ed25519_syntek.pub
echo ""
echo "-------------------------------------------"
echo "MISSIONAL GEN ($MG_GITHUB_USER)"
echo "https://github.com/settings/keys"
echo "-------------------------------------------"
cat ~/.ssh/id_ed25519_mg.pub
echo ""

# ============================================
# CREATE REPO DIRECTORIES
# ============================================
echo "=== Creating Repository Directories ==="
mkdir -p ~/Repos/personal
mkdir -p ~/Repos/syntek
mkdir -p ~/Repos/missional-gen
echo "✓ ~/Repos/personal"
echo "✓ ~/Repos/syntek"
echo "✓ ~/Repos/missional-gen"
echo ""

# ============================================
# TEST INSTRUCTIONS
# ============================================
echo "============================================"
echo "=== NEXT STEPS ==="
echo "============================================"
echo ""
echo "1. Copy each public key above and add to the respective GitHub account:"
echo "   → Login to GitHub as $PERSONAL_GITHUB_USER, go to Settings > SSH Keys, add Personal key"
echo "   → Login to GitHub as $SYNTEK_GITHUB_USER, go to Settings > SSH Keys, add Syntek key"
echo "   → Login to GitHub as $MG_GITHUB_USER, go to Settings > SSH Keys, add Missional Gen key"
echo ""
echo "2. Test each connection:"
echo "   ssh -T git@github-personal"
echo "   ssh -T git@github-syntek"
echo "   ssh -T git@github-missionalgen"
echo ""
echo "3. Clone repos using the correct host alias:"
echo "   git clone git@github-personal:$PERSONAL_GITHUB_USER/repo.git ~/Repos/personal/repo"
echo "   git clone git@github-syntek:$SYNTEK_GITHUB_USER/repo.git ~/Repos/syntek/repo"
echo "   git clone git@github-missionalgen:$MG_GITHUB_USER/repo.git ~/Repos/missional-gen/repo"
echo ""
echo "4. Continue with zedconfig installation:"
echo "   git clone git@github-personal:$PERSONAL_GITHUB_USER/zedconfig.git ~/Repos/personal/zedconfig"
echo "   cd ~/Repos/personal/zedconfig"
echo "   chmod +x *.sh"
echo "   ./install.sh --deps"
echo "   ./install.sh"
echo "   ./verify-setup.sh"
echo ""

if [[ "$IS_WSL" == true ]]; then
    echo "=== WSL Note ==="
    echo "These SSH keys are stored in your WSL Linux environment."
    echo "They are separate from any Windows SSH keys."
    echo ""
fi

echo "=== SSH Setup Complete ==="
