# Hardware Configuration for Intel i5-10210U Laptop
# Generated by 'nixos-generate-config' and adapted for this flake.
#
# BTRFS on LUKS with subvolumes: @root, @home, @nix, @snapshots, @log

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # CPU - Intel i5-10210U (Comet Lake)
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # LUKS encrypted root
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/4cf4afe8-4076-4249-b963-9d29bd918458";

  # BTRFS subvolumes (all on the same LUKS-decrypted filesystem)
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fc7428cf-f919-46b8-aaae-1a99d927aa93";
    fsType = "btrfs";
    options = [ "subvol=@root" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fc7428cf-f919-46b8-aaae-1a99d927aa93";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/fc7428cf-f919-46b8-aaae-1a99d927aa93";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/fc7428cf-f919-46b8-aaae-1a99d927aa93";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/fc7428cf-f919-46b8-aaae-1a99d927aa93";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8EAE-C635";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # No swap partition (BTRFS + LUKS setup)
  swapDevices = [ ];

  # Hardware configuration
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
