[package]
name = "agenix-helper"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "agenix-helper"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
colored = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
which = { workspace = true }
walkdir = { workspace = true }
