[package]
name = "secrets-verify"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "secrets-verify"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
colored = { workspace = true }
anyhow = { workspace = true }
walkdir = { workspace = true }
which = { workspace = true }
dirs = { workspace = true }
