[package]
name = "luks-manage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "luks-manage"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
colored = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
which = { workspace = true }
libc = { workspace = true }
