# Agenix secrets configuration
# This file defines which secrets exist and which machines can decrypt them
#
# Per-Device Security Model:
#   - User keys: Per-device keys for agenix encrypt/decrypt during development
#   - Host keys: Machine SSH keys for decryption during nixos-rebuild
#   - GitHub keys: Per-device keys WITHOUT passphrases (convenience)
#   - Server/VPN/VM keys: Per-device keys WITH passphrases (security)
#   - Device compromise only exposes keys for THAT device
#
# Setup per device:
#   1. Generate a dedicated agenix user key:
#      ssh-keygen -t ed25519 -C "sam@<device>" -f ~/.ssh/id_ed25519_agenix
#   2. Paste the public key below for that device
#   3. After rekeying, that device can encrypt/decrypt secrets:
#      agenix -i ~/.ssh/id_ed25519_agenix -e <secret>.age

let
  # ============================================================================
  # User keys (per-device, for encrypting/decrypting secrets during development)
  # These let YOU run `agenix -e` on each machine you edit secrets from.
  # Generate with: ssh-keygen -t ed25519 -C "sam@<device>" -f ~/.ssh/id_ed25519_agenix
  # Get public key: cat ~/.ssh/id_ed25519_agenix.pub
  # ============================================================================
  sam-laptop = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDDdE+EkEkG7BtvLb5mDPC6bPbs0vzw1yq6xcfmv+hao sam@laptop-intel";
  # sam-ubuntu = "ssh-ed25519 REPLACE_WITH_UBUNTU_PC_USER_KEY sam@ubuntu-pc";

  # ============================================================================
  # Host keys (machine SSH host keys - extracted after NixOS installation)
  # Each NixOS machine generates these during installation at /etc/ssh/ssh_host_ed25519_key.pub
  # Get them with: ssh-keyscan <hostname> or cat /etc/ssh/ssh_host_ed25519_key.pub
  # ============================================================================
  laptop-intel = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIPZckL/JszhuspKDhEsd5LpD4b4GvM2WPHFgHUAc29v root@laptop-intel";
  # framework = "ssh-ed25519 REPLACE_WITH_FRAMEWORK_HOST_KEY root@framework";
  # devtower = "ssh-ed25519 REPLACE_WITH_DEVTOWER_HOST_KEY root@devtower";

  # Key groups for easy management (only include keys with real values)
  allUsers = [ sam-laptop ];
  allHosts = [ laptop-intel ];
  allKeys = allUsers ++ allHosts;

  # Specific device groups (uncomment when devices are set up)
  # laptops = [ laptop-intel framework ];
  # desktops = [ devtower ];
in
{
  # ============================================================================
  # GitHub SSH Keys (Per-Device, NO Passphrases)
  # Each device has its own key for each GitHub account
  # Benefits: Device compromise only exposes that device's keys
  # ============================================================================

  # Personal GitHub (SamBailey6194)
  "github-ssh-personal-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "github-ssh-personal-framework.age".publicKeys = allUsers ++ [ framework ];
  # "github-ssh-personal-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # Syntek GitHub (syntek-studio)
  "github-ssh-syntek-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "github-ssh-syntek-framework.age".publicKeys = allUsers ++ [ framework ];
  # "github-ssh-syntek-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # Missional Gen GitHub (sam-missionalgen)
  "github-ssh-missionalgen-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "github-ssh-missionalgen-framework.age".publicKeys = allUsers ++ [ framework ];
  # "github-ssh-missionalgen-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # ============================================================================
  # Mullvad WireGuard VPN (Per-Device Configuration)
  # Phase 6: Multi-hop VPN with split tunneling and automatic rotation
  # Each device has: private key, account number, config, cache, route history
  # ============================================================================

  # Wireguard private keys (generated by wireguard-helper init)
  "wireguard-laptop-intel-private.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "wireguard-framework-private.age".publicKeys = allUsers ++ [ framework ];
  # "wireguard-devtower-private.age".publicKeys = allUsers ++ [ devtower ];

  # Mullvad account numbers (from mullvad.net)
  # TODO: Uncomment when wireguard-helper multi-hop rotation is implemented
  # "mullvad-account-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "mullvad-account-framework.age".publicKeys = allUsers ++ [ framework ];
  # "mullvad-account-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # Generated multi-hop configs (rotated by wireguard-helper)
  # "mullvad-wg-config-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "mullvad-wg-config-framework.age".publicKeys = allUsers ++ [ framework ];
  # "mullvad-wg-config-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # API cache and route history (avoid reusing servers)
  # "mullvad-relay-cache-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "mullvad-relay-cache-framework.age".publicKeys = allUsers ++ [ framework ];
  # "mullvad-relay-cache-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # "mullvad-route-history-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "mullvad-route-history-framework.age".publicKeys = allUsers ++ [ framework ];
  # "mullvad-route-history-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # ============================================================================
  # Malware Scanner Quarantine Encryption Keys (Per-Device)
  # Phase 7: Malware detection and threat protection
  # Each device has its own encryption key for quarantine storage
  # 256-bit AES-GCM keys for encrypting quarantined malware samples
  # ============================================================================

  "malware-scanner-quarantine-key-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "malware-scanner-quarantine-key-framework.age".publicKeys = allUsers ++ [ framework ];
  # "malware-scanner-quarantine-key-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # ============================================================================
  # LUKS Encryption Passphrases (Per-Device Fallback Recovery)
  # These are fallback passphrases when TPM2 auto-unlock fails
  # DevTower has separate passphrases for OS, home, and media drives
  # ============================================================================

  # Laptop LUKS passphrases (single drive)
  "luks-passphrase-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "luks-passphrase-framework.age".publicKeys = allUsers ++ [ framework ];

  # DevTower LUKS passphrases (3 separate drives)
  # "luks-passphrase-devtower-os.age".publicKeys = allUsers ++ [ devtower ];      # /dev/nvme1n1p2 (OS)
  # "luks-passphrase-devtower-home.age".publicKeys = allUsers ++ [ devtower ];    # /dev/sdd1 (Home)
  # "luks-passphrase-devtower-media.age".publicKeys = allUsers ++ [ devtower ];   # /dev/sdc1 (Media)

  # ============================================================================
  # Per-Folder Encryption Master Keys (gocryptfs)
  # Optional master keys for vault recovery (users can also use passwords only)
  # ============================================================================

  "vault-master-key-laptop-intel.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "vault-master-key-framework.age".publicKeys = allUsers ++ [ framework ];
  # "vault-master-key-devtower.age".publicKeys = allUsers ++ [ devtower ];

  # ============================================================================
  # Server SSH Keys (Per-Device, WITH Passphrases)
  # Example: Client ACME server - each device has unique credentials
  # Format: server-<name>-<device>-key.age (private key)
  #         server-<name>-<device>-passphrase.age (passphrase)
  # ============================================================================

  # Example: Uncomment when adding your first client server
  "server-acme-laptop-intel-key.age".publicKeys = allUsers ++ [ laptop-intel ];
  "server-acme-laptop-intel-passphrase.age".publicKeys = allUsers ++ [ laptop-intel ];
  # "server-acme-framework-key.age".publicKeys = allUsers ++ [ framework ];
  # "server-acme-framework-passphrase.age".publicKeys = allUsers ++ [ framework ];
  # "server-acme-devtower-key.age".publicKeys = allUsers ++ [ devtower ];
  # "server-acme-devtower-passphrase.age".publicKeys = allUsers ++ [ devtower ];

  # ============================================================================
  # Shared Secrets (All Devices Can Decrypt)
  # Use sparingly - prefer per-device secrets for zero-trust
  # ============================================================================

  # Example: Uncomment when needed
  # "wifi-passwords.age".publicKeys = allKeys;
  # "api-tokens-read-only.age".publicKeys = allKeys;
  # "restic-backup-password.age".publicKeys = allKeys;

  # ============================================================================
  # Device-Specific Secrets (Only One Device)
  # Example: Production database credentials only on devtower
  # ============================================================================

  # Example: Uncomment when needed
  # "production-db-password.age".publicKeys = allUsers ++ [ devtower ];
  # "staging-api-key.age".publicKeys = allUsers ++ laptops;
}
